routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Api\TagController;
use App\Http\Controllers\Api\PageController;
use App\Http\Controllers\Api\PostController;
use App\Http\Controllers\Api\SiteController;
use App\Http\Controllers\Api\TaskController;
use App\Http\Controllers\Api\TeamController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\MediaController;
use App\Http\Controllers\Api\UploadController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\ProjectController;
use App\Http\Controllers\Api\ServiceController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\QuestionController;
use App\Http\Controllers\Api\TestimonyController;
use App\Http\Controllers\Api\NewsletterController;

Route::get('/admin/login', function () {
    return view('admin');
});

Route::prefix('admin/')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('', AdminController::class)->name('admin');
        Route::resource('services', ServiceController::class);
        Route::resource('messages', MessageController::class);
        Route::resource('testimonies', TestimonyController::class);
        Route::resource('questions', QuestionController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('posts', PostController::class);
        Route::resource('projects', ProjectController::class);
        Route::resource('tags', TagController::class);

        Route::post('/pages/uploads', [PageController::class, 'uploadImage'])->name('pages.upload.image');
        Route::resource('pages', PageController::class);

        Route::get('users/profile', [UserController::class, 'profile'])->name('users.profile');
        Route::put('users/password/update', [UserController::class, 'passwordUpdate'])->name('users.password.update');
        Route::put('users/profile', [UserController::class, 'profileUpdate'])->name('users.profile.update');
        Route::put('users/profile/avatar', [UserController::class, 'uploadAvatar'])->name('users.upload.avatar');
        Route::resource('users', UserController::class);
        Route::resource('teams', TeamController::class);
        Route::resource('newsletters', NewsletterController::class)->only(['index', 'destroy']);

        Route::get('/tasks', [TaskController::class, 'index'])->name('tasks.index');
        Route::post('/tasks', [TaskController::class, 'process'])->name('tasks.process');



        Route::get('/site', [SiteController::class, 'edit'])->name('site.edit');
        Route::put('/site', [SiteController::class, 'update'])->name('site.update');
        Route::post('/logout', [AdminController::class, 'logout'])->name('admin.logout');

        Route::post('filepond-process', [UploadController::class, 'filepondProcess'])->name('filepond-process');
        Route::delete('filepond-revert', [UploadController::class, 'filepondRevert'])->name('filepond-revert');
        Route::delete('filepond-remove', [UploadController::class, 'filepondRemove'])->name('filepond-remove');
        Route::post('uploads', [UploadController::class, 'uploads'])->name('uploads.image');
        Route::get('media', [MediaController::class, 'index'])->name('media.index');
        Route::get('media/list', [MediaController::class, 'list'])->name('media.list');
        Route::delete('media/{media}', [MediaController::class, 'destroy'])->name('media.destroy');
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\QuestionController;

Route::get('/', HomeController::class)->name('welcome');
Route::get('/services', [ServiceController::class, 'index'])->name('services.list');
Route::get('/services/{service:slug}', [ServiceController::class, 'show'])->name('services.detail');

Route::get('/portfolio', [ProjectController::class, 'index'])->name('portfolio');
Route::get('/portfolio/tags/{tag:name}', [ProjectController::class, 'index'])->name('portfolio.tag');
Route::get('/portfolio/{project:name}', [ProjectController::class, 'show'])->name('projects.detail');

Route::get('/blog', [BlogController::class, 'index'])->name(('posts.list'));
Route::get('/blog/category/{slug}', [BlogController::class, 'index'])->name(('posts.category'));
Route::get('/blog/{post:slug}', [BlogController::class, 'detail'])->name(('posts.detail'));

Route::get('/contact', function () {
    return view('contact');
})->name(('pages.contact'));


Route::get('/about-us', function () {
    return view('about-us');
})->name(('about-us'));

Route::get('/faq', [QuestionController::class, 'index'])->name(('faq'));

Route::get('/privacy-policy', [PageController::class, 'privacyPolicy'])->name(('privacy-policy'));

Route::get('/blog', [BlogController::class, 'index'])->name(('blog'));

Route::post('/message', MessageController::class);




require __DIR__ . DIRECTORY_SEPARATOR . 'admin.php';

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('layouts.admin');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('layouts.base');
    }
}

resources/views/about-us.blade.php
<x-app-layout>
    @section('title')
        | Apropos de nous
    @endsection
    <!-- Hero about us  -->
    <section class="bg-hero-pattern py-[120px] mt-[60px] hero-contact" id="hero-contact">
        <div class="container">
            <div class="flex items-center justify-center">
                <h1 class="text-fs-3 md:text-fs-1 hero-title">Ce que nous faisons</h1>
            </div>
        </div>
    </section>

    <!-- About Us -->
    <section class="contact section">
        <div class="container">
            <div class="grid  md:grid-cols-2 gap-[30px] items-center">
                <h2 class="text-fs-3 md:text-[50px] font-700 leading-[1.5]">NOTRE ÉQUIPE EST VOTRE ÉQUIPE</h2>
                <p class="text-fs-5 leading-[1.6] title-underline">
                    Nous sommes un groupe d'experts d'esprits divers qui associent stratégie, technologie et passion
                    créative pour concevoir
                    la meilleure expérience pour votre marque.
                </p>
            </div>
        </div>
    </section>

    <!-- About Us Image full -->
    <section class="my-[60px] section about-us-full  bg-no-repeat bg-cover bg-center w-full h-[534px]"
        style="background-image: url('{{ asset('images/about-us-full.jpeg') }}')">
    </section>

    <section class="contact section">
        <div class="container">
            <div class="grid  md:grid-cols-3 gap-[10px] items-start">
                <h2 class="text-fs-1 leading-[1.2]">À PROPOS DE NOUS</h2>
                <div class="col-span-2">
                    <p class="text-fs-7 leading-[1.6] mb-[10px]">
                        WelyaCreative fait partie des acteurs de la transition numérique en Guinée. Notre agence Web &
                        Digital propose une
                        approche 360°, orientée autour des besoins de notre clientèle, de l’analyse des données et de
                        l’expérience utilisateur.
                        Nous appliquons des méthodologies éprouvées à l’ensemble de nos services, soit la conception, le
                        design UX/UI et le
                        développement de MVPs, sites Internet, e-commerce, marketplaces et applications mobiles ;
                        l’hébergement et la
                        maintenance de services digitaux.
                    </p>
                    <p class="text-fs-7 leading-[1.6]">
                        Depuis + de 5 ans, notre agence digitale perfectionne sa méthode pour concevoir des expériences
                        qui
                        suscitent
                        l’engagement de vos utilisateurs et génèrent des résultats pour votre entreprise. Notre mission
                        ?
                        Façonner l'UX pour
                        humaniser vos produits et services.
                    </p>
                </div>
            </div>
            <div class="py-[50px]">
                <h3 class="text-center">Ce qui nous differencie des autres?</h3>
                <p class="text-fs-7 mb-[5px]">Depuis 2019, nous croisons nos compétences en conseil stratégique,
                    développement
                    technique, design
                    d’interface et
                    conception centrée utilisateur pour produire des supports web ultra-efficaces. Notre recette ? Faire
                    collaborer des
                    humains bourrés de talents, prêts à relever les défis les plus fous (ou presque) au service de l'UX
                    et du RSI.</p>
                <p class="text-fs-7">Nous concevons des expériences digitales uniques qui engagent vos utilisateurs,
                    vous démarquent de la
                    concurrence et
                    prennent soin de votre RSI(Retour Sur Investissement). Création ou refonte de site internet,
                    application mobile, outils
                    métiers, web app, Création des contenues medias, Marketing digital et le Comminuty management : nos
                    experts en UX
                    Design, stratégie digitale, design d'interfaces et développement technique conçoivent votre projet
                    en (re)plaçant
                    l’humain au centre de la conception.</p>
            </div>
        </div>
    </section>

    <!-- Let's talk -->
    <section class="lets-talk">
        <div class="container grid place-content-center">
            <h1>Let’s talk</h1>
            <p class=""><a href="mailto:contact@welyacreative.com">hey@welyacreative.com</a></p>
        </div>
    </section>

    @include('partials.newsletter')


</x-app-layout>

resources/views/admin.blade.php
<x-admin-layout>
    <div id="app" class="w-screen h-screen overflow-x-hidden overflow-y-scroll"></div>
</x-admin-layout>

resources/views/blog.blade.php
@push('scripts')
    <script>
        const categorySelect = document.getElementById('category-select')
        categorySelect.addEventListener('change', ({
            target
        }) => {
            const {
                value: catId
            } = target
            const url = "{{ route('blog') }}/" + (catId ? `category/${catId}` : "")
            location.replace(url)
        })
    </script>
@endpush

<x-app-layout>
    @section('title')
        | Blog
    @endsection
    @if ($posts->isEmpty())
    <section class="py-[120px]">
        <div class="container">
            <h3 class="text-center">Aucun article pour le moment</h3>
        </div>
    </section>
    @else
        <section class="pt-[120px]">
            <div class="container">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div class="flex flex-col gap-8">
                        <div class="flex gap-16">
                            <div class="text-gray-500 uppercase">{{ $latestPost->created_at->isoFormat('LL') }}</div>
                            <div class="text-gray-500 uppercase">Auteur {{ $latestPost->author->name }}</div>
                        </div>
                        <h1 class="text-fs-3 md:text-fs-2">{{ $latestPost->title }}</h1>
                        <a href="{{ route('posts.detail', $latestPost) }}" class="uppercase font-bold text-primary">Voire
                            plus</a>
                    </div>
                    <img src="{{ $latestPost->imageMedium }}" class="w-full" width="420" height="320"
                        alt="">
                </div>
            </div>
        </section>
        <section class="block-list py-32">
            <div class="container">
                <div class="flex items-center justify-end py-16">
                    <span class="mr-2">Catégorie:</span>
                    <select name="category" id="category-select" class="py-4 text-fs-8 rounded shadow">
                        <option value="">Toutes les catégories</option>
                        @foreach ($categories as $cat)
                            <option value="{{ $cat->id }}" {{ $catId === $cat->id ? 'selected' : '' }}>
                                {{ $cat->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    @foreach ($posts as $post)
                        <a href="{{ route('posts.detail', $post) }}" class="flex flex-col justify-between border">
                            <img src="{{ $post->imageMedium }}" class="h-[250px]" alt="">
                            <div class="px-6 pb-4 rounded">
                                <h4 class="text-fs-6 text-secondary my-4 hover:text-primary">{{ $post->title }}</h4>
                                <div class="flex justify-between py-2">
                                    <div class="text-gray-500 uppercase text-xl">
                                        {{ $post->created_at->isoFormat('LL') }}
                                    </div>
                                    <div class="text-gray-500 uppercase text-xl">Auteur {{ $post->author->name }}</div>
                                </div>
                                <p class="mb-8">
                                    {{ $post->excerpt }}
                                </p>
                                <div class="uppercase font-medium text-primary">Voire plus</div>
                            </div>
                        </a>
                    @endforeach
                </div>
                <div class="py-16">
                    {{ $posts->links('vendor.pagination.tailwind') }}
                </div>
            </div>
        </section>
    @endif


    <div class="bg-gradient-primary py-32 mb-16 md:mb-32">
        <div class="container">
            <div class="flex flex-col md:flex-row gap-16">
                <div>
                    <h3 class="text-fs-2 text-white">Démarrer un projet</h3>
                    <p class="text-gray-400">Avec une équipe complète d'experts à votre disposition, <br> tout est
                        possible</p>
                </div>
                <div class="card flex-grow">
                    @include('partials.contact-form')
                </div>
            </div>
        </div>
    </div>
    @include('partials.newsletter')
</x-app-layout>

resources/views/contact.blade.php
<x-app-layout>
    @section('title')
        | Contact
    @endsection

    <!-- Hero contact -->
    <section class="py-[120px] hero-contact bg-gradient-primary" id="hero-contact">
        <div class="container">
            <div class="grid place-content-center">
                <h1 class="hero-title">Prêt à gagner plus d'affaires?</h1>
                <p class="text-slate-200 font-500 text-fs-6">Appelez-nous au +224 622064449 ou contactez-nous dès
                    aujourd'hui</p>
            </div>
        </div>
    </section>

    <!-- Contact -->
    <section class="contact section">
        <div class="container">
            <h2 class="text-center">Contactez-nous</h2>
            <p class="text-fs-8 text-center mb-[30px]">Parlez-nous de votre projet.
            </p>
            <div class="card shadow-2xl">
                <div class="grid lg:grid-cols-2 gap-8">
                    <img src="{{ asset('images/contact-us.jpg') }}"
                        class="hidden lg:block w-full h-full rounded-lg md:object-contain lg:object-cover" alt="contact us">
                    @include('partials.contact-form')
                </div>
            </div>
        </div>
    </section>

    <!-- Socials and address    -->
    <section class="contact-social-and-address" id="contact-social-and-address">
        <div class="container">
            <h3 class="md:text-center mb-[30px]">
                Adresses & Réseaux sociaux
            </h3>
            <div class="flex flex-col md:flex-row  justify-between items-center gap-16">
                <div class="self-start">
                    <p class="text-fs-7 text-secondary mb-2">Sur les réseaux sociaux</p>
                    <div class="flex gap-4">
                        <a href="" class="social-link bg-primary hover:bg-white group">
                            <svg class="social-link-icon group-hover:fill-primary" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" width="24" height="24">
                                <path fill="none" d="M0 0h24v24H0z" />
                                <path
                                    d="M12 2C6.477 2 2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.879V14.89h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.989C18.343 21.129 22 16.99 22 12c0-5.523-4.477-10-10-10z" />
                            </svg>
                        </a>
                        <a href="" class="social-link bg-primary hover:bg-white group">
                            <svg class="social-link-icon group-hover:fill-primary" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" width="24" height="24">
                                <path fill="none" d="M0 0h24v24H0z" />
                                <path
                                    d="M15.3 5.55a2.9 2.9 0 0 0-2.9 2.847l-.028 1.575a.6.6 0 0 1-.68.583l-1.561-.212c-2.054-.28-4.022-1.226-5.91-2.799-.598 3.31.57 5.603 3.383 7.372l1.747 1.098a.6.6 0 0 1 .034.993L7.793 18.17c.947.059 1.846.017 2.592-.131 4.718-.942 7.855-4.492 7.855-10.348 0-.478-1.012-2.141-2.94-2.141zm-4.9 2.81a4.9 4.9 0 0 1 8.385-3.355c.711-.005 1.316.175 2.669-.645-.335 1.64-.5 2.352-1.214 3.331 0 7.642-4.697 11.358-9.463 12.309-3.268.652-8.02-.419-9.382-1.841.694-.054 3.514-.357 5.144-1.55C5.16 15.7-.329 12.47 3.278 3.786c1.693 1.977 3.41 3.323 5.15 4.037 1.158.475 1.442.465 1.973.538z" />
                            </svg>
                        </a>
                        <a href="" class="social-link bg-primary hover:bg-white group">
                            <svg class="social-link-icon group-hover:fill-primary" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" width="24" height="24">
                                <path fill="none" d="M0 0h24v24H0z" />
                                <path
                                    d="M19.606 6.995c-.076-.298-.292-.523-.539-.592C18.63 6.28 16.5 6 12 6s-6.628.28-7.069.403c-.244.068-.46.293-.537.592C4.285 7.419 4 9.196 4 12s.285 4.58.394 5.006c.076.297.292.522.538.59C5.372 17.72 7.5 18 12 18s6.629-.28 7.069-.403c.244-.068.46-.293.537-.592C19.715 16.581 20 14.8 20 12s-.285-4.58-.394-5.005zm1.937-.497C22 8.28 22 12 22 12s0 3.72-.457 5.502c-.254.985-.997 1.76-1.938 2.022C17.896 20 12 20 12 20s-5.893 0-7.605-.476c-.945-.266-1.687-1.04-1.938-2.022C2 15.72 2 12 2 12s0-3.72.457-5.502c.254-.985.997-1.76 1.938-2.022C6.107 4 12 4 12 4s5.896 0 7.605.476c.945.266 1.687 1.04 1.938 2.022zM10 15.5v-7l6 3.5-6 3.5z" />
                            </svg>
                        </a>
                        <a href="" class="social-link bg-primary hover:bg-white group">
                            <svg class="social-link-icon group-hover:fill-primary" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24" width="24" height="24">
                                <path fill="none" d="M0 0h24v24H0z" />
                                <path
                                    d="M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm1 2v14h14V5H5zm2.5 4a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm-1 1h2v7.5h-2V10zm5.5.43c.584-.565 1.266-.93 2-.93 2.071 0 3.5 1.679 3.5 3.75v4.25h-2v-4.25a1.75 1.75 0 0 0-3.5 0v4.25h-2V10h2v.43z" />
                            </svg>
                        </a>
                    </div>
                </div>
                <!-- Addresses -->
                <div class="flex flex-col self-start">
                    <p class="text-fs-7 text-secondary mb-2">Contactez nous</p>
                    <div class="flex gap-4 flex-col text-fs-8 mb-[10px]">
                        <div class="flex items-center gap-4">
                            <span class="social-link bg-primary hover:bg-white group">
                                <svg class="social-link-icon group-hover:fill-primary"
                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                    height="24">
                                    <path fill="none" d="M0 0h24v24H0z" />
                                    <path
                                        d="M9.366 10.682a10.556 10.556 0 0 0 3.952 3.952l.884-1.238a1 1 0 0 1 1.294-.296 11.422 11.422 0 0 0 4.583 1.364 1 1 0 0 1 .921.997v4.462a1 1 0 0 1-.898.995c-.53.055-1.064.082-1.602.082C9.94 21 3 14.06 3 5.5c0-.538.027-1.072.082-1.602A1 1 0 0 1 4.077 3h4.462a1 1 0 0 1 .997.921A11.422 11.422 0 0 0 10.9 8.504a1 1 0 0 1-.296 1.294l-1.238.884zm-2.522-.657l1.9-1.357A13.41 13.41 0 0 1 7.647 5H5.01c-.006.166-.009.333-.009.5C5 12.956 11.044 19 18.5 19c.167 0 .334-.003.5-.01v-2.637a13.41 13.41 0 0 1-3.668-1.097l-1.357 1.9a12.442 12.442 0 0 1-1.588-.75l-.058-.033a12.556 12.556 0 0 1-4.702-4.702l-.033-.058a12.442 12.442 0 0 1-.75-1.588z" />
                                </svg>
                            </span>
                            <div class="flex flex-col gap-1">
                                <a href="">622 06 44 49</a>
                                <a href="">622 06 44 49</a>
                            </div>
                        </div>
                    </div>
                    <!-- Emails -->
                    <div class="flex gap-4 flex-col text-fs-8 mb-[10px]">
                        <div class="flex items-center gap-4">
                            <span class="social-link bg-primary hover:bg-white group">
                                <svg class="social-link-icon group-hover:fill-primary"
                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                    height="24">
                                    <path fill="none" d="M0 0h24v24H0z" />
                                    <path
                                        d="M3 3h18a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm17 4.238l-7.928 7.1L4 7.216V19h16V7.238zM4.511 5l7.55 6.662L19.502 5H4.511z" />
                                </svg>
                            </span>
                            <div class="flex flex-col gap-1">
                                <a href="">contact@welyacreative.com</a>
                                <a href="">admin@welyacreative.com</a>
                            </div>
                        </div>
                    </div>

                    <!-- Addresses -->
                    <div class="flex gap-4 flex-col text-fs-8">
                        <div class="flex items-center gap-4">
                            <span class="social-link bg-primary hover:bg-white group ">
                                <svg class="social-link-icon group-hover:fill-primary"
                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                    height="24">
                                    <path fill="none" d="M0 0h24v24H0z" />
                                    <path
                                        d="M18.364 17.364L12 23.728l-6.364-6.364a9 9 0 1 1 12.728 0zM12 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm0-2a2 2 0 1 1 0-4 2 2 0 0 1 0 4z" />
                                </svg>
                            </span>
                            <div class="flex flex-col gap-1">
                                <a href="">Sonfonia Foula Madina</a>
                                <a href="">Boké, Fria</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    @include('partials.newsletter')
</x-app-layout>

resources/views/privacy-policy.blade.php
<x-app-layout>
    @section('title')
        | Politique de confidentialité
    @endsection
    <section class="policy py-32">
        <div class="container">
            <div class="py-6">
                <h1>{{ $page->title }}</h1>
            </div>
            <div>
                {!! $page->content !!}
            </div>
        </div>
    </section>
</x-app-layout>

resources/views/questions.blade.php
<x-app-layout>
    @section('title')
        | FAQ GÉNÉRALE
    @endsection
    <section class="py-[120px] bg-gradient-primary" id="hero-faq">
        <div class="container">
            <div class="grid place-content-center">
                <p class="text-white">FAQ GÉNÉRALE.</p>
                <h1 class="hero-title">Des réponses à vos questions</h1>
            </div>
        </div>
    </section>
    <section class="faq py-16 md:py-32" id="faq">
        <div class="container">
            <div>
                @foreach ($questions as $q)
                    <div x-data="{ open: false }" class="mb-6 border rounded-t-lg">
                        <div x-on:click="open = !open"
                            class="p-2 cursor-pointer bg-primary/10 rounded-t-lg flex justify-between hover:bg-primary/40"
                            :class="open ? 'bg-primary/40' : ''">
                            <h4 class="text-fs-6  text-secondary">{{ $q->question }}</h4>
                            <div>
                                <svg x-show="open" class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                    <path
                                        d="M11.9997 10.8284L7.04996 15.7782L5.63574 14.364L11.9997 8L18.3637 14.364L16.9495 15.7782L11.9997 10.8284Z">
                                    </path>
                                </svg>
                                <svg x-show="!open" class="w-8 h-8" xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 24 24">
                                    <path
                                        d="M11.9997 13.1714L16.9495 8.22168L18.3637 9.63589L11.9997 15.9999L5.63574 9.63589L7.04996 8.22168L11.9997 13.1714Z">
                                    </path>
                                </svg>
                            </div>
                        </div>
                        <div class="px-2 py-4" x-show="open" x-transition>
                            <p>{{ $q->answer }}</p>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

    <section class="bg-gradient-primary py-16">
        <div class="container">
            <div class="flex flex-col md:flex-row gap-16">
                <div>
                    <h3 class="text-fs-2 text-white">Démarrer un projet</h3>
                    <p class="text-gray-400">Avec une équipe complète d'experts à votre disposition, <br> tout est
                        possible</p>
                </div>
                <div class="card flex-grow">
                    @include('partials.contact-form')
                </div>
            </div>
        </div>
    </section>
    @include('partials.newsletter')
</x-app-layout>